var _hshClr = (fill, stroke) => {
    return {
        fill: fill || "#ffffff",
        stroke: stroke || "rgb(153, 153, 153)"
    }
};

var clrByType = {
    "base64":        _hshClr("#DEBD5C"),
    "batch":         _hshClr("#E2D96E"),
    "catch":         _hshClr("#e49191"),
    "change":        _hshClr("#E2D96E"),
    "rbe":           _hshClr("#E2D96E"), 
    "comment":       _hshClr(),
    "complete":      _hshClr("rgb(192, 237, 192)"),
    "csv":           _hshClr("#DEBD5C"),
    "debug":         _hshClr("#87a980"),
    "delay":         _hshClr("#E6E0F8"),
    "exec":          _hshClr("#e9967a"),
    "feedparse":     _hshClr("#C0DEED"),
    "file":          _hshClr("#deb887"),
    "file in":       _hshClr("#deb887"),
    "function":      _hshClr("#fdd0a2"),
    "html":          _hshClr("#DEBD5C"),
    "http response": _hshClr("rgb(231, 231, 174)"),
    "http in":       _hshClr("rgb(231, 231, 174)"),
    "http request":  _hshClr("rgb(231, 231, 174)"),
    "inject":        _hshClr("#a6bbcf"),
    "join":          _hshClr("#E2D96E"),
    "json":          _hshClr("#DEBD5C"),
    "junction":      _hshClr('rgb(217, 217, 217)'),
    "link in":       _hshClr("#ddd"),
    "link out":      _hshClr("#ddd"),
    "link call":     _hshClr("#ddd"),
    "markdown":      _hshClr("#DEBD5C"),
    "mqtt in":       _hshClr("rgb(216, 191, 216)"),
    "mqtt out":      _hshClr("rgb(216, 191, 216)"),
    "postgresql":    _hshClr("#5b85a7"),
    "range":         _hshClr("#E2D96E"),
    "sort":          _hshClr("#E2D96E"),
    "split":         _hshClr("#E2D96E"),
    "subflow":       _hshClr("#ddd"),
    "status":        _hshClr("rgb(148, 193, 208)"),
    "switch":        _hshClr("#E2D96E"),
    "trigger":       _hshClr("#E6E0F8"),
    "tcp in":        _hshClr("#c0c0c0"),
    "tcp out":       _hshClr("#c0c0c0"),
    "tcp request":   _hshClr("#c0c0c0"),
    "udp in":        _hshClr("#c0c0c0"),
    "udp out":       _hshClr("#c0c0c0"),
    ui_button:       _hshClr("rgb(176, 223, 227)"),
    ui_list:         _hshClr("rgb( 63, 173, 181)"),
    ui_svg_graphics: _hshClr("rgb( 63, 173, 181)"),
    ui_template:     _hshClr("rgb( 63, 173, 181)"),
    ui_toast:        _hshClr("rgb(119, 198, 204)"),
    ui_upload:       _hshClr("rgb( 63, 173, 181)"),
    ui_audio:        _hshClr("rgb(119, 198, 204)"),
    ui_chart:        _hshClr("rgb(119, 198, 204)"),
    ui_gauge:        _hshClr("rgb(119, 198, 204)"),
    ui_text:         _hshClr("rgb(119, 198, 204)"),
    ui_date_picker:  _hshClr("rgb(176, 223, 227)"),
    ui_dropdown:     _hshClr("rgb(176, 223, 227)"),
    ui_form:         _hshClr("rgb(176, 223, 227)"),
    ui_numeric:      _hshClr("rgb(176, 223, 227)"),
    ui_slider:       _hshClr("rgb(176, 223, 227)"),
    ui_switch:       _hshClr("rgb(176, 223, 227)"),
    ui_text_input:   _hshClr("rgb(176, 223, 227)"),
    ui_colour_picker: _hshClr("rgb(176, 223, 227)"),

    "websocket in":  _hshClr("rgb(215, 215, 160)"),
    "websocket out": _hshClr("rgb(215, 215, 160)"),
    "yaml":          _hshClr("#DEBD5C"),
    "xml":           _hshClr("#DEBD5C"),

    /* private nodes for this instane */
    'BlogPages':    _hshClr("#ddeeff"),
    'BlogDetails':  _hshClr("#ddeeff"),
    'BlogPageInfo': _hshClr("#ddeeff"),
    'BlogChanges':  _hshClr("#ddeeff"),
    'PubMedium':    _hshClr("#ddee44"),

    "Topic": _hshClr('#d0c9f6'),
    "Observation": _hshClr('#f4adf3'),
    "Question": _hshClr('#e0a4f3'),
    "Thought": _hshClr('#cb9cf3'),
    "Idea": _hshClr('#88baff'),
    "Analogy": _hshClr('#86bfff'),
    "Aphorism": _hshClr('#84c3ff'),
    "Poesie": _hshClr('#82C6FF'),
    "Humour": _hshClr('#81C9FF'),
    "Treasure": _hshClr('#80CCFF'),
    "Consequence": _hshClr('#f6c1cc'),
    "Advantage": _hshClr('#efacbf'),
    "Disadvantage": _hshClr('#e796b1'),
    "Text": _hshClr('#c8ffb5'),
    "Blog-Post": _hshClr('#CDFEBC'),
    "Comment": _hshClr('#D2FDC3'),
    "Code-Base": _hshClr('#D7FCCB'),
    "Sketch": _hshClr('#e1fbda'),
    "Inspiration": _hshClr('#dfdfb6'),
    "Quote": _hshClr('#E3E3BE'),
    "Definition": _hshClr('#E7E8C6'),
    "Book": _hshClr('#F0F1D6'),
    "Author": _hshClr('#f5f6de'),
    "Dream": _hshClr('#86BDFF'),
    "Art": _hshClr('#DCFBD2'),
    "Image": _hshClr('#CDFEBC'),
    "Metaphor": _hshClr('#85C0FF'),
    "Learning": _hshClr('#e1fbda'),
    "Keyword": _hshClr('#E2E2BB'),
    "Bookmark": _hshClr('#ECECCE'),
    
    'nnb-input-node': _hshClr('#ffefef'),
    'nnb-layer-node': _hshClr('#ffffef'),
    'nnb-output-node': _hshClr('#efefef'),
    'nnb-backprop': _hshClr('#e3edef'),
    'nnb-trainer': _hshClr('#e5e4ef'),

    'Seeker': _hshClr('#e5e4ef'),
    'Sink': _hshClr('#e5e4ef'),
    'Screenshot': _hshClr('#e5e4ef'),
    'Orphans': _hshClr('#e5e4ef'),
    'IsMobile': _hshClr('#e5e4ef'),
    'Navigator': _hshClr('#e5e4ef'),
    'DrawSVG': _hshClr('#e5e4ef'),
    'GetFlows': _hshClr('#e5e4ef'),
    'SendFlow': _hshClr('#e5e4ef'),
    'InstallPackage': _hshClr('#e5e4ef'),
    'TriggerImport': _hshClr('#e5e4ef'),
    'ClientCode': _hshClr('#e5e4ef'),

    "i2c scan": _hshClr('rgb(227, 82, 83)'),
    "i2c in": _hshClr('rgb(227, 82, 83)'),
    "i2c out": _hshClr('rgb(227, 82, 83)'),

    "NodeFactory": _hshClr('#e5e4ef'),
    "NodeRedInstall": _hshClr('#e5e4ef'),
    "PkgFile": _hshClr('#e5e4ef'),
    "NpmTarBall": _hshClr('#e5e4ef'),
    "NpmPublish": _hshClr('#e5e4ef'),
    "NodeDevOps": _hshClr('#e5e4ef'),
    "OTPGenerate": _hshClr('#e5e4ef'),
    
    'cronplus': _hshClr('#a6bbcf'),

    "FlowHubPull": _hshClr("#44eeff"),
    "FlowHubPush": _hshClr("#44eeff"),
    "FlowHubDiff": _hshClr("#44eeff"),
    
    "JsonSchemaValidatorWithDocu": _hshClr("#addb7b"),
    "Flow2UML": _hshClr("#C0DDFF"),

    "AutoAlign": _hshClr("#DDD7A0"),
    "UglifyJS": _hshClr("#D7D7A0"),

    "aedes broker": _hshClr("rgb(216, 191, 216)"),

    "Blockly": _hshClr("#FFAAAA"),
    "osc": _hshClr("#0099FF"),
    
    "sphere": _hshClr('#D8BFD8'),
    "box": _hshClr('#D8BFD8'),
    "plane": _hshClr('#D8BFD8'),
    "cone": _hshClr('#D8BFD8'),
    "transform": _hshClr('#D8BFD8'),
    "events": _hshClr('#D8BFD8'),

    "AIsBreaker": _hshClr('#1AE0F0'),
    
    "PipeStart": _hshClr('#e5e4ef'),
    "FileStream": _hshClr('#D7D7A0'),
    "HttpRequestStream": _hshClr('#D7D7A0'),
    "CsvStream": _hshClr('#FDD0A2'),
    "JsonLStream": _hshClr('#FDD0A2'),
    "LineStream": _hshClr('#FDD0A2'),
    "IconvStream": _hshClr('#FDD0A2'),
    "Chunk2Msg": _hshClr('#FDD0A2'),
    "DeCompStream": _hshClr('#FDF0C2'),
    "ArchiveStream": _hshClr('#FDF0C2'),
    "PipeEnd": _hshClr('#e5e4ef'),

    "Yaml2Flow": _hshClr('#e5e4ef'),

    "Contact": _hshClr('#e5e4ef'),
    "EmptyContact": _hshClr('#E9967A'),
    "Generator": _hshClr('#e5e4ef'),

    "ArtWork": _hshClr("#FDD0A284"),

    "ut-assert-failure": _hshClr("#FFAAAA"),
    "ut-assert-values": _hshClr('#FDF0C2'),
    "ut-assert-success": _hshClr('#addb7b'),
    "ut-assert-status": _hshClr('#C0DEED'),
    "ut-assert-debug": _hshClr('#D8BFD8'),

    "erlsupervisor": _hshClr('#E9967A'),
    "erlmodule": _hshClr("#fdd0a2"),
    "erlstatemachine": _hshClr("#FFCC66"),
    "erleventhandler": _hshClr("#FFCC66"),

    "mermaid-flowchart": _hshClr("#C7E9C0"),

    "_default": _hshClr("rgb(243, 181, 103)")
};